
export const ComboboxOptionsOfGender = [
  "男性", "女性", "回答しない"
]

export const ComboboxOptionsOfAddress = [
  { label: "北海道", group: "北海道" },
  { label: "青森県", group: "東北地方" },
  { label: "岩手県", group: "東北地方" },
  { label: "宮城県", group: "東北地方" },
  { label: "秋田県", group: "東北地方" },
  { label: "山形県", group: "東北地方" },
  { label: "福島県", group: "東北地方" },
  { label: "茨城県", group: "関東地方" },
  { label: "栃木県", group: "関東地方" },
  { label: "群馬県", group: "関東地方" },
  { label: "埼玉県", group: "関東地方" },
  { label: "千葉県", group: "関東地方" },
  { label: "東京都", group: "関東地方" },
  { label: "神奈川県", group: "関東地方" },
  { label: "山梨県", group: "関東地方" },
  { label: "長野県", group: "関東地方" },
  { label: "新潟県", group: "北陸地方" },
  { label: "富山県", group: "北陸地方" },
  { label: "石川県", group: "北陸地方" },
  { label: "福井県", group: "北陸地方" },
  { label: "岐阜県", group: "中部地方" },
  { label: "静岡県", group: "中部地方" },
  { label: "愛知県", group: "中部地方" },
  { label: "三重県", group: "中部地方" },
  { label: "滋賀県", group: "近畿地方" },
  { label: "京都府", group: "近畿地方" },
  { label: "大阪府", group: "近畿地方" },
  { label: "兵庫県", group: "近畿地方" },
  { label: "奈良県", group: "近畿地方" },
  { label: "和歌山県", group: "近畿地方" },
  { label: "鳥取県", group: "中国地方" },
  { label: "島根県", group: "中国地方" },
  { label: "岡山県", group: "中国地方" },
  { label: "広島県", group: "中国地方" },
  { label: "山口県", group: "中国地方" },
  { label: "徳島県", group: "四国地方" },
  { label: "香川県", group: "四国地方" },
  { label: "愛媛県", group: "四国地方" },
  { label: "高知県", group: "四国地方" },
  { label: "福岡県", group: "九州地方" },
  { label: "佐賀県", group: "九州地方" },
  { label: "長崎県", group: "九州地方" },
  { label: "熊本県", group: "九州地方" },
  { label: "大分県", group: "九州地方" },
  { label: "宮崎県", group: "九州地方" },
  { label: "鹿児島県", group: "九州地方" },
  { label: "沖縄県", group: "九州地方" },
]